// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: system/system.proto

package system

import (
	_ "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求消息
type CheckUpgradeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=apiKey,proto3" json:"apiKey"` // 平台认证用 API Key
	AppKey        string                 `protobuf:"bytes,2,opt,name=appKey,proto3" json:"appKey"` // 应用唯一标识，例如：'redd'
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUpgradeReq) Reset() {
	*x = CheckUpgradeReq{}
	mi := &file_system_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpgradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpgradeReq) ProtoMessage() {}

func (x *CheckUpgradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpgradeReq.ProtoReflect.Descriptor instead.
func (*CheckUpgradeReq) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{0}
}

func (x *CheckUpgradeReq) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CheckUpgradeReq) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

// 响应消息
type CheckUpgradeResp struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BuildBuildVersion      string                 `protobuf:"bytes,1,opt,name=buildBuildVersion,proto3" json:"buildBuildVersion"`           // 构建版本
	ForceUpdateVersion     string                 `protobuf:"bytes,2,opt,name=forceUpdateVersion,proto3" json:"forceUpdateVersion"`         // 强制更新的版本号
	ForceUpdateVersionNo   string                 `protobuf:"bytes,3,opt,name=forceUpdateVersionNo,proto3" json:"forceUpdateVersionNo"`     // 强制更新的内部版本号
	NeedForceUpdate        bool                   `protobuf:"varint,4,opt,name=needForceUpdate,proto3" json:"needForceUpdate"`              // 是否强制更新
	DownloadURL            string                 `protobuf:"bytes,5,opt,name=downloadURL,proto3" json:"downloadURL"`                       // 安装包下载链接
	BuildHaveNewVersion    bool                   `protobuf:"varint,6,opt,name=buildHaveNewVersion,proto3" json:"buildHaveNewVersion"`      // 是否有新版本
	BuildVersionNo         string                 `protobuf:"bytes,7,opt,name=buildVersionNo,proto3" json:"buildVersionNo"`                 // 内部版本号
	BuildVersion           string                 `protobuf:"bytes,8,opt,name=buildVersion,proto3" json:"buildVersion"`                     // 可见版本号
	BuildUpdateDescription string                 `protobuf:"bytes,9,opt,name=buildUpdateDescription,proto3" json:"buildUpdateDescription"` // 更新说明
	AppKey                 string                 `protobuf:"bytes,10,opt,name=appKey,proto3" json:"appKey"`                                // 应用标识（回传）
	BuildKey               string                 `protobuf:"bytes,11,opt,name=buildKey,proto3" json:"buildKey"`                            // 构建的唯一标识
	BuildName              string                 `protobuf:"bytes,12,opt,name=buildName,proto3" json:"buildName"`                          // 应用名称
	BuildIcon              string                 `protobuf:"bytes,13,opt,name=buildIcon,proto3" json:"buildIcon"`                          // 应用图标链接
	BuildFileKey           string                 `protobuf:"bytes,14,opt,name=buildFileKey,proto3" json:"buildFileKey"`                    // 安装包文件标识
	BuildFileSize          string                 `protobuf:"bytes,15,opt,name=buildFileSize,proto3" json:"buildFileSize"`                  // 文件大小（单位：字符串表示的字节数）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CheckUpgradeResp) Reset() {
	*x = CheckUpgradeResp{}
	mi := &file_system_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUpgradeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUpgradeResp) ProtoMessage() {}

func (x *CheckUpgradeResp) ProtoReflect() protoreflect.Message {
	mi := &file_system_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUpgradeResp.ProtoReflect.Descriptor instead.
func (*CheckUpgradeResp) Descriptor() ([]byte, []int) {
	return file_system_system_proto_rawDescGZIP(), []int{1}
}

func (x *CheckUpgradeResp) GetBuildBuildVersion() string {
	if x != nil {
		return x.BuildBuildVersion
	}
	return ""
}

func (x *CheckUpgradeResp) GetForceUpdateVersion() string {
	if x != nil {
		return x.ForceUpdateVersion
	}
	return ""
}

func (x *CheckUpgradeResp) GetForceUpdateVersionNo() string {
	if x != nil {
		return x.ForceUpdateVersionNo
	}
	return ""
}

func (x *CheckUpgradeResp) GetNeedForceUpdate() bool {
	if x != nil {
		return x.NeedForceUpdate
	}
	return false
}

func (x *CheckUpgradeResp) GetDownloadURL() string {
	if x != nil {
		return x.DownloadURL
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildHaveNewVersion() bool {
	if x != nil {
		return x.BuildHaveNewVersion
	}
	return false
}

func (x *CheckUpgradeResp) GetBuildVersionNo() string {
	if x != nil {
		return x.BuildVersionNo
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildUpdateDescription() string {
	if x != nil {
		return x.BuildUpdateDescription
	}
	return ""
}

func (x *CheckUpgradeResp) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildKey() string {
	if x != nil {
		return x.BuildKey
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildName() string {
	if x != nil {
		return x.BuildName
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildIcon() string {
	if x != nil {
		return x.BuildIcon
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildFileKey() string {
	if x != nil {
		return x.BuildFileKey
	}
	return ""
}

func (x *CheckUpgradeResp) GetBuildFileSize() string {
	if x != nil {
		return x.BuildFileSize
	}
	return ""
}

var File_system_system_proto protoreflect.FileDescriptor

const file_system_system_proto_rawDesc = "" +
	"\n" +
	"\x13system/system.proto\x12\ropenim.system\x1a\x11sdkws/sdkws.proto\"A\n" +
	"\x0fCheckUpgradeReq\x12\x16\n" +
	"\x06apiKey\x18\x01 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06appKey\x18\x02 \x01(\tR\x06appKey\"\xe0\x04\n" +
	"\x10CheckUpgradeResp\x12,\n" +
	"\x11buildBuildVersion\x18\x01 \x01(\tR\x11buildBuildVersion\x12.\n" +
	"\x12forceUpdateVersion\x18\x02 \x01(\tR\x12forceUpdateVersion\x122\n" +
	"\x14forceUpdateVersionNo\x18\x03 \x01(\tR\x14forceUpdateVersionNo\x12(\n" +
	"\x0fneedForceUpdate\x18\x04 \x01(\bR\x0fneedForceUpdate\x12 \n" +
	"\vdownloadURL\x18\x05 \x01(\tR\vdownloadURL\x120\n" +
	"\x13buildHaveNewVersion\x18\x06 \x01(\bR\x13buildHaveNewVersion\x12&\n" +
	"\x0ebuildVersionNo\x18\a \x01(\tR\x0ebuildVersionNo\x12\"\n" +
	"\fbuildVersion\x18\b \x01(\tR\fbuildVersion\x126\n" +
	"\x16buildUpdateDescription\x18\t \x01(\tR\x16buildUpdateDescription\x12\x16\n" +
	"\x06appKey\x18\n" +
	" \x01(\tR\x06appKey\x12\x1a\n" +
	"\bbuildKey\x18\v \x01(\tR\bbuildKey\x12\x1c\n" +
	"\tbuildName\x18\f \x01(\tR\tbuildName\x12\x1c\n" +
	"\tbuildIcon\x18\r \x01(\tR\tbuildIcon\x12\"\n" +
	"\fbuildFileKey\x18\x0e \x01(\tR\fbuildFileKey\x12$\n" +
	"\rbuildFileSize\x18\x0f \x01(\tR\rbuildFileSize2Y\n" +
	"\x06system\x12O\n" +
	"\fCheckUpgrade\x12\x1e.openim.system.CheckUpgradeReq\x1a\x1f.openim.system.CheckUpgradeRespB&Z$github.com/openimsdk/protocol/systemb\x06proto3"

var (
	file_system_system_proto_rawDescOnce sync.Once
	file_system_system_proto_rawDescData []byte
)

func file_system_system_proto_rawDescGZIP() []byte {
	file_system_system_proto_rawDescOnce.Do(func() {
		file_system_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)))
	})
	return file_system_system_proto_rawDescData
}

var file_system_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_system_system_proto_goTypes = []any{
	(*CheckUpgradeReq)(nil),  // 0: openim.system.CheckUpgradeReq
	(*CheckUpgradeResp)(nil), // 1: openim.system.CheckUpgradeResp
}
var file_system_system_proto_depIdxs = []int32{
	0, // 0: openim.system.system.CheckUpgrade:input_type -> openim.system.CheckUpgradeReq
	1, // 1: openim.system.system.CheckUpgrade:output_type -> openim.system.CheckUpgradeResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_system_system_proto_init() }
func file_system_system_proto_init() {
	if File_system_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_system_proto_rawDesc), len(file_system_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_system_proto_goTypes,
		DependencyIndexes: file_system_system_proto_depIdxs,
		MessageInfos:      file_system_system_proto_msgTypes,
	}.Build()
	File_system_system_proto = out.File
	file_system_system_proto_goTypes = nil
	file_system_system_proto_depIdxs = nil
}
